pipelines:
  kartotherian:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: production-kartotherian
        publish:
          type: image
          tags: [kartotherian]
  tilerator:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: production-tilerator
        publish:
          type: image
          tags: [tilerator]
