pipelines:
  kartotherian:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: production-kartotherian
        build: production-kartotherian
        publish:
          type: image
          tags: [kartotherian]

